appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
shippable:
  projectId: 5c32d1a7d1578b0700305ba7
  secure: {BINSTAR_TOKEN: bkTdATvev7sVFsP62xFV2ck215nXEtH7eWXdhzRRtbzeKquSkNhTGTCoa5FcLDvAVe36w+Sv59/3/oWNyMood8pIWjHLMC5CqqLdc4NRmyyaCKWys4CLhTTurIBPFSWUilxZW1KCKv/WHOe+zQDi2o9R9lf5/MizuwThHSQOIcqeTIn4wtPzbne5MeKSW+mRCsb+l4E/Q1oY2w/mTJ+izDWkxefstZ2t8RqOxH6H20wwNOOj/1WdeztdCOtCAl99r8Aj58odGyfUMAEyw89c5HglAEPurBQs21DZbHp10NmgSLyIbukplulRUm+cQ37loT/hFfTjPUCqLEC3lu6SPw==}
travis:
  secure: {BINSTAR_TOKEN: vgMRcKwg/iiBexj7AJ44xs+DY/+u/5CdBWMuUnPJdXxtCrJprweAU3y0SS8PJ/7mPePFvMmx70tAdWK+Wjqfpx58Sawqyr/ylK8vjLR+3JajxT3xdN5a3coGo5XNTwyKmCSD9VjnxIA85/7Q177USqWRIOt1EAp0r+gI1RRNuG96MV3PHdnbKAOuAriLcHni8ysGSKzEjwmXfwr1Ns+tu0dgYBSIEGkJV0ubn9BnJUMonoJHmKcuNhNS7vjYrzMrY1gdHTVV5CnA2y9X39P9lvNMHWONkoS3BLcuZXI7mIsXokpL4Kj96ruLkzFiritt4Q7EmR8eFRUMMz8mMFI1eqLe6eyjFvVtQv9FT0lbtAHVWBy49ZRJS4eJyU0okT3tJkZsRlAspUZQK3FgN5ycyjecW9sHHaAPdvunRzZ/iyi+RUP5jobEnJVy3U4Gm1Gea8pC0BxRrY3XtDTruo32B4e3g5XHwQ/GQ2Hpff3CkKr3k0l6/lvD1Hi8WzORGb2t/yIOUGFypMQiTFNMNBimytObNPSmITQcKeN6d64OUUp2vavvM9GLC9Fh1WhlZR2ljr0VdRswyJfVu/M4wDiigve9dXxcU+IEePDKN+5hg1qDFum0nd6IAOtzNenXsr3W4PDWOS49haRPsw6CqA9FX6Ubx3CuRrolJLWzh62ieiU=}
